server:
  port: 9011
spring:
  application:
    name: tensquare-user #指定服务名
jwt:
  config:
    key: itcast
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    tensquare-base:
      path: /gathering/**
      serviceId: tensquare-base